/**
 * project match-match-r-r
 */
const ActionTypes = {
    USER_NAME: 'USER_NAME',
    USER_ID: 'USER_ID',
    SAVE_RECORD: 'SAVE_RECORD',
    SET_DIFFICULTY: 'SET_DIFFICULTY',
    SET_SKIRT: 'SET_SKIRT',
    SET_DECK: 'SET_DECK',
    CARD_DRAWING: 'CARD_DRAWING',
    CARD_DRAWN: 'CARD_DRAWN',
    CARD_OPENING: 'CARD_OPENING',
    CARDS_CLOSING: 'CARDS_CLOSING',
    CARDS_HIDING: 'CARDS_HIDING',
    SHOWED_CARD: 'SHOWED_CARD',
    SET_TIMEOUT: 'SET_TIMEOUT',
    TOTAL_RECORDS: 'TOTAL_RECORDS',
    LOADING_DATA: 'LOADING_DATA',
    START_TIMER: 'START_TIMER',
    TICK: 'TICK',
    NEW_GAME: 'NEW_GAME',
    SHOW_LOGIN_FORM: 'SHOW_LOGIN_FORM',
    CHECK_NAME: 'NAME_VALID',
    CHECK_EMAIL: 'EMAIL_VALID',
    CHECK_PASSWORD: 'PASSWORD_VALID',
};

export default ActionTypes;
