/**
 * project match-match-r-r
 */
const ActionTypes = {
    // player actions
    LOGIN_PLAYER: 'LOGIN_PLAYER',
    REGISTRATION_OR_LOG_FAIL: 'REGISTRATION_OR_LOG_FAIL',
    LOGIN_FAILED: 'LOGIN_FAILED',
    REG_PLAYER: 'REG_PLAYER',
    SET_PLAYER: 'SET_PLAYER',
    SAVE_RECORD: 'SAVE_RECORD',
    // deck actions
    CHOOSE_CARD: 'CHOOSE_CARD',
    DRAW_CARD: 'DRAW_CARD',
    OPEN_CARD: 'OPEN_CARD',
    CLOSE_CARD: 'CLOSE_CARD',
    HIDE_CARD: 'HIDE_CARD',
    // game actions
    SET_DECK: 'SET_DECK',
    CLEAR_DECK: 'CLEAR_DECK',
    NEW_GAME_INIT: 'NEW_GAME_INIT',
    END_GAME: 'END_GAME',
    SET_DIFFICULTY: 'SET_DIFFICULTY',
    SET_TIMEOUT: 'SET_TIMEOUT',
    SET_SKIRT: 'SET_SKIRT',
    START_TIMER: 'START_TIMER',
    RESET_TIME: 'RESET_TIME',
    TICK: 'TICK',
    SET_PANDA: 'SET_PANDA',
    // app action
    GET_RECORDS: 'GET_RECORDS',
    DATA_LOADING: 'DATA_LOADING',
};

export default ActionTypes;
