/**
 * project match-match-r-r
 */
const ActionTypes = {
    // player actions
    SAVE_PLAYER: 'SAVE_PLAYER',
    SAVE_RECORD: 'SAVE_RECORD',
    // card actions
    CARD_DRAWING: 'CARD_DRAWING',
    CARD_DRAWN: 'CARD_DRAWN',
    CARD_OPENING: 'CARD_OPENING',
    CARD_OPENED: 'CARD_OPENED',
    CARDS_CLOSING: 'CARDS_CLOSING',
    CARD_CLOSED: 'CARD_CLOSED',
    CARDS_HIDING: 'CARDS_HIDING',
    // game actions
    SET_DECK: 'SET_DECK',
    DECK_DRAWING: 'DRAWING_DECK',
    DECK_DRAWN: 'DECK_DRAWN',
    SET_DIFFICULTY: 'SET_DIFFICULTY',
    SET_SKIRT: 'SET_SKIRT',
    SHOWED_CARDS: 'SHOWED_CARDS',
    HIDDEN_CARDS: 'HIDDEN_CARDS',
    START_TIMER: 'START_TIMER',
    TICK: 'TICK',
    NEW_GAME: 'NEW_GAME',
    // app action
    TOTAL_RECORDS_LOADED: 'TOTAL_RECORDS_LOADED',
    HIDE_MAIN_MENU: 'HIDE_MAIN_MENU',
    DROP_MAIN_MENU: 'DROP_MAIN_MENU',
    DATA_LOADING: 'DATA_LOADING',
};

export default ActionTypes;
